//export var images: Map<> = new Map([
  // ["RU", ],
  // ["UF", { name: 'UF',position: 1, orientation: 0 }],
  // ["FU", { name: 'FU',position: 1, orientation: 1 }],
  // ["UL", { name: 'UL',position: 2, orientation: 0 }],
  // ["LU", { name: 'LU',position: 2, orientation: 1 }],
  // ["UB", { name: 'UB',position: 3, orientation: 0 }],
  // ["BU", { name: 'BU',position: 3, orientation: 1 }],
  // ["DR", { name: 'DR',position: 4, orientation: 0 }],
  // ["RD", { name: 'RD',position: 4, orientation: 1 }],
  // ["DF", { name: 'DF',position: 5, orientation: 0 }],
  // ["FD", { name: 'FD',position: 5, orientation: 1 }],
  // ["DL", { name: 'DL',position: 6, orientation: 0 }],
  // ["LD", { name: 'LD',position: 6, orientation: 1 }],
  // ["DB", { name: 'DB',position: 7, orientation: 0 }],
  // ["BD", { name: 'BD',position: 7, orientation: 1 }],
  // ["FR", { name: 'FR',position: 8, orientation: 0 }],
  // ["RF", { name: 'RF',position: 8, orientation: 1 }],
  // ["FL", { name: 'FL',position: 9, orientation: 0 }],
  // ["LF", { name: 'LF',position: 9, orientation: 1 }],
  // ["BL", { name: 'BL',position: 10, orientation: 0 }],
  // ["LB", { name: 'LB',position: 10, orientation: 1 }],
  // ["BR", { name: 'BR',position: 11, orientation: 0 }],
  // ["RB", { name: 'RB',position: 11, orientation: 1 }],
//]);
